version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: learn-nestjs-prisma
    ports:
      - 5462:5432
    env_file:
      - .postgres.env
    volumes:
      - db-postgres:/var/lib/postgresql/data

volumes:
  db-postgres: